spring:
  application:
    name: Digital Library

  datasource:
    url: jdbc:h2:mem:testdb  # or just remove the entire datasource section
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: none

  #  data:
  #    redis:
  #      host: <your-host>
  #      port: <your-port>
  #      password: <your-password> [Optional]

  security:
    user:
      name: shantanu
      password: shantanu

    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liPdO1w3BUBR7ys5
            client-secret: 07be37e1de7757b32f5027d580bc3f69a6562112
            scope: read:user
            redirect-uri: http://localhost:8080/login/oauth2/code/github